### ISSUE TITLE
goa integration

### ISSUE THREAD

**Issue by joeblew99** [PalmStoneGames/polymer#10]
The integration of go-polymer with goa is looking great.

**Comment by luna-duclos** [comment]
How would this work ? I'm not familiar with goa at all and would like to know more about what you have in mind

**Comment by joeblew99** [comment]
well goa is a code generator.
you define your API, and model. It then code generates all the code form
the db up.

Its written such that you can easily add plugins to generate client side
code.
but it could also generate go code that will be run through gopherjs.
The type of code thats obviously smart is the client proxy code for calling
the server & the client model types.

I have found others doing this too.
for angular2, there is a cli that can scaffold out the code. So this could
be run from goa to generate the js
there is also a react one i have seen. but it does nto generate the client
code yet.

does that help ?

**Comment by luna-duclos** [comment]
Yes! Thank you. I'd certainly be interested in this. I do not currently have the time to work on this myself, but this might change in the future

**Comment by joeblew99** [comment]
cool.

I did 2 project in polymer, before i started using gopherjs.
Its partly how i found you.
But i found Polymer still very beta, with lots of loose edges.
For the current projects i am very happy with Angular2, Ionic2

In respect of gopherJS integration, i am still in 2 minds.
Because Angular2 and Ionic 2 uses typescript, we get allot of design time
strong typing for free.

But i think that using goa DSL / codegen to generate the code for Angular
makes a ton of sense and fits very well..

There is a group specifically working on this.
