### ISSUE TITLE
code.palmstonegames.com SSL cert is expired

### ISSUE THREAD

**Issue by emmaly** [PalmStoneGames/polymer#16]
The code.palmstonegames.com SSL cert is expired, which is causing `go get` for this package to fail.

```
user@e2c5a1e9cd1a:~$ go get -u -v code.palmstonegames.com/polymer
Fetching https://code.palmstonegames.com/polymer?go-get=1
https fetch failed: Get https://code.palmstonegames.com/polymer?go-get=1: x509: certificate has expired or is not yet valid
package code.palmstonegames.com/polymer: unrecognized import path "code.palmstonegames.com/polymer" (https fetch: Get https://code.palmstonegames.com/polymer?go-get=1: x509: certificate has expired or is not yet valid)
```

**Comment by emmaly** [comment]
Temporary workaround I used:

```
$ go get -u -v github.com/PalmStoneGames/polymer
$ mv $GOPATH/src/github.com/PalmStoneGames $GOPATH/src/code.palmstonegames.com
```

This assumes these things:
- `$GOPATH` has only one path in it
- `$GOPATH/src/github.com/PalmStoneGames` only contains `polymer`
- `$GOPATH/src/code.palmstonegames.com` doesn't exist yet

**Comment by dmitshur** [comment]
`go get` has a [`-insecure` flag](https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies) which can also be used as a workaround. It is as the name implies.

**Comment by luna-duclos** [comment]
The correct answer is likely to use the github URL, I'll remove the import comment

**Comment by emmaly** [comment]
If the ```code.palmstonegames.com``` import path is going away, https://github.com/gopherjs/gopherjs/wiki/bindings should be updated to reflect that as well.

**Comment by dmitshur** [comment]
Yep, if the import path has changed, that page should be updated to use the latest. Would you like to update it, @dustywilson?
